/**
 * Template source v1.1.0 — Beztack auth package.
 *
 * Template-owned. Pure platform logic; Derived projects do not edit this file.
 * The corresponding Derived project file is at packages/auth/session.ts.
 */

export interface Session {
  readonly userId: string;
  readonly expiresAt: number;
}

export function createSession(userId: string): Session {
  return {
    userId,
    expiresAt: Date.now() + 60 * 60 * 1000,
  };
}

export function isSessionExpired(session: Session): boolean {
  return session.expiresAt <= Date.now();
}
