/**
 * Template source v1.2.0 — Beztack auth package.
 *
 * Template-owned. Pure platform logic; Derived projects do not edit this file.
 * This revision adds `rotateSession` and tightens the expiration window to
 * 30 minutes. Any Derived project with a Custom-owned change to this file
 * (e.g., the overlap case in the fixture) MUST be reported as overlap or
 * conflict, never silently merged.
 */

export interface Session {
  readonly userId: string;
  readonly expiresAt: number;
  readonly rotatedFrom?: string;
}

export const SESSION_TTL_MS = 30 * 60 * 1000;

export function createSession(userId: string): Session {
  return {
    userId,
    expiresAt: Date.now() + SESSION_TTL_MS,
  };
}

export function rotateSession(session: Session): Session {
  return {
    userId: session.userId,
    expiresAt: Date.now() + SESSION_TTL_MS,
    rotatedFrom: session.userId,
  };
}

export function isSessionExpired(session: Session): boolean {
  return session.expiresAt <= Date.now();
}
